language: node_js
node_js:
  - "10.16.1"

script:
  - npm test
  - npm run build

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    application: "codedeploy"
    deployment_group: "githubdeploy"
    region: "ap-southeast-1"